# Generated by Django 4.0.3 on 2022-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('email', models.CharField(default='mail', max_length=255)),
                ('contact', models.BigIntegerField(default='070000000')),
                ('university', models.CharField(default='university', max_length=255)),
                ('start_date', models.DateField(default='2022-01-01')),
                ('end_date', models.DateField(default='2022-03-30')),
                ('supervisor', models.CharField(default='supervisor', max_length=255)),
                ('department', models.CharField(default='department', max_length=255)),
            ],
        ),
    ]
