# Generated by Django 4.0.3 on 2022-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachee_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2022-06-22')),
                ('floor', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=2550)),
                ('Resolved', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=2550)),
            ],
        ),
    ]
