# Generated by Django 4.0.3 on 2022-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachee_reg_form', '0002_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
