# Generated by Django 4.0.3 on 2022-06-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachee_reg_form', '0003_admin_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_code',
            new_name='Code',
        ),
    ]
